#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
#include "images/mc-day.h"
#include "images/mc-night.h"
#include "images/steve.h"


int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  int buttonWasDown[NBUTTONS] = {0};
  int buttonJustReleased[NBUTTONS] = {0};

  // Load initial application state
  struct game_state cs, ps;

  struct game_state starting_state = {
    START,
    0,
    {0, 0, 0, 0, -2},
    {0, 0, 0, 0},
    0,
    -1,
  };

  while (1) {
    ps = cs;

    for (int i=0; i<NBUTTONS; i++) {
			buttonJustReleased[i] = KEY_DOWN(i, BUTTONS) == 0 && buttonWasDown[i];
			buttonWasDown[i] = KEY_DOWN(i, BUTTONS) != 0;
		}

    if (buttonJustReleased[BUTTON_SELECT_IND]) {
      cs.gba_state = START;
    }

    switch (cs.gba_state) {
      case START:
        cs = starting_state;
        
        if (buttonJustReleased[BUTTON_START_IND]) {
          cs.gba_state = BUILD;
        }

        break;
      case BUILD:
        cs.gba_state = PLAY;
        break;
      case PLAY:

      UNUSED(0);

        if (videoBuffer[OFFSET(cs.player.row - 2, cs.player.col, WIDTH)] == CYAN) {
          cs.gba_state = WIN;
          cs.winTick = cs.ticks;
          break;
        }

        int moveInc = 1;

        if (cs.player.jump != -1) {
          
          int jumpPower[] = {-10, -7, -5, -2, -1, 0, 1, 2, 7, 10};
          int jumpPowerLen = 9;

          int vertMoveInc = cs.player.jump <= jumpPowerLen 
            ? jumpPower[cs.player.jump]
            : jumpPower[jumpPowerLen];
          
          int hitGround = 0;

          for (int i=0; i < vertMoveInc; i++) {
            if (videoBuffer[OFFSET(cs.player.row + i, cs.player.col, WIDTH)] == GREEN) {
              vertMoveInc = i;
              hitGround = 1;
            }
          }
          
          cs.player.row += vertMoveInc;
          cs.player.jump = hitGround ? -1 : cs.player.jump + 1;
        } else {
          if (
            videoBuffer[OFFSET(cs.player.row, cs.player.col - cs.player.cd/2, WIDTH)] != GREEN &&
            videoBuffer[OFFSET(cs.player.row, cs.player.col - cs.player.cd/2, WIDTH)] != BROWN &&
            videoBuffer[OFFSET(cs.player.row, cs.player.col - cs.player.cd/2, WIDTH)] != GRAY
          ) {
            cs.player.row += 2;
          }
          
        }

        if (buttonWasDown[BUTTON_LEFT_IND]) {
          if (
            cs.player.col - cs.player.cd <= 0 || 
            videoBuffer[OFFSET(cs.player.row - cs.player.rd, cs.player.col - moveInc, WIDTH)] == GREEN ||
            videoBuffer[OFFSET(cs.player.row - cs.player.rd, cs.player.col - moveInc, WIDTH)] == BROWN ||
            videoBuffer[OFFSET(cs.player.row - cs.player.rd, cs.player.col - moveInc, WIDTH)] == GRAY
          ) {
            break;
          }
          cs.player.col -= moveInc;
        }

        if (buttonWasDown[BUTTON_RIGHT_IND]) {
          if (
            cs.player.col + cs.player.cd >= WIDTH || 
            videoBuffer[OFFSET(cs.player.row - 1, cs.player.col , WIDTH)] == GREEN ||
            videoBuffer[OFFSET(cs.player.row - 1, cs.player.col , WIDTH)] == BROWN ||
            videoBuffer[OFFSET(cs.player.row - 1, cs.player.col , WIDTH)] == GRAY
          ) {
            break;
          }
          cs.player.col += moveInc;
        }

        if (buttonJustReleased[BUTTON_UP_IND] && cs.player.jump == -1) {
          cs.player.jump = 0;
        }

        // state = ?
        break;
      case WIN:

        // state = ?
        break;
    }

    waitForVBlank();

    switch (cs.gba_state) {
      case START:

        fillScreenDMA(GREEN);
        drawCenteredString(20, WIDTH/2, 6, 80, "GAMEBOY MINECRAFT", WHITE);
        drawCenteredString(60, WIDTH/2, 6, 80, "PRESS START", WHITE);
  
        // state = ?
        break;
      case BUILD:

        // background
        drawFullScreenImageDMA(mcday);

        // terrain
        int grassHeight = 2;
        int dirtHeight = 5;

        int heightDiff = 0;
        for (int i=0; i<3; i++) {
          int width = i*80;
          if (i > 0) heightDiff += randint(-10, -5);
          drawRectDMA(HEIGHT/2 + heightDiff, width, WIDTH/3, grassHeight, GREEN);
          drawRectDMA(HEIGHT/2 + grassHeight + heightDiff, width, WIDTH/3, dirtHeight, BROWN);
          drawRectDMA(HEIGHT/2 + grassHeight + dirtHeight + heightDiff, width, WIDTH/3, HEIGHT, GRAY);
        }

        // diamond
        drawRectDMA(HEIGHT/2 + heightDiff - 5, WIDTH - 10, 5, 5, CYAN);

        // createw new player potentially
        if (cs.player.jump == -2) {
          struct player newPlayer = (struct player) {
            HEIGHT/2,
            15,
            10,
            4,
            -1
          };
          cs.player = newPlayer;
        }
        
        drawImageDMA(cs.player.row - cs.player.rd, cs.player.col - cs.player.cd, cs.player.cd, cs.player.rd, steve);
			
        cs.gba_state = PLAY;
        break;
      case PLAY:
      
        
        undrawImageDMA(ps.player.row - ps.player.rd, ps.player.col - ps.player.cd, ps.player.cd, ps.player.rd, mcday);
        // setPixel(cs.player.row, cs.player.col, RED);
        drawImageDMA(cs.player.row - cs.player.rd, cs.player.col - cs.player.cd, cs.player.cd, cs.player.rd, steve);

        // tet
        char timeString[100];
        sprintf(timeString, "GET THE DIAMOND! TIME: %d.%d s", cs.ticks / 60, (cs.ticks/6) % 10);
        drawRectDMA(HEIGHT - 10, 2, 200, 10, GRAY);
        drawString(HEIGHT - 10, 2, timeString, WHITE);
        // state = ?
        break;
      case WIN:

        if (cs.ticks - cs.winTick == 1) {
          drawFullScreenImageDMA(mcnight);
        }
        if (cs.ticks - cs.winTick == 100) {
          drawCenteredString(30+1, WIDTH/2+1, 6, 80, "YOU WIN", RED);
          drawCenteredString(30, WIDTH/2, 6, 80, "YOU WIN", WHITE);
        }
        if (cs.ticks - cs.winTick > 200) {
          drawCenteredString(40+1, WIDTH/2+1, 6, 80, "GOOD JOB", RED);
          drawCenteredString(40, WIDTH/2, 6, 80, "GOOD JOB", WHITE);
        } if (cs.ticks - cs.winTick > 300) {
          char timeString[100];
          sprintf(timeString, "WINNING TIME: %d.%d s", cs.winTick / 60, (cs.winTick/6) % 10);
          drawCenteredString(50+1, WIDTH/2+1, 6, 80, timeString, RED);
          drawCenteredString(50, WIDTH/2, 6, 80, timeString, WHITE);
        }
        // state = ?
        break;
    }

    cs.ticks++;
  }

  return 0;
}
